//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionManagement.Database {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransactionManagement.Database.SQL", typeof(SQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Valon Hoti @ 2010-07-04 [YYYY-MM-DD]
        ///-- Prishtine,10000
        ///-- KOSOVE
        ///-- DATABASE : Northwind 
        ///-- ORIGIN   : MS SQL 
        ///-- SOURCE   : SQLITE 3
        ///-- 
        ///-- Converted TABLES and VIEWS from MS SQL 2000  to Sqlite 3 
        ///-- 
        ///
        ///-- Modified by Len Boyette @ 2013-02-08
        ///-- Added foreign keys
        ///
        ///
        ///-- Categories
        ///DROP TABLE IF EXISTS [Categories];
        ///CREATE TABLE [Categories]
        ///(      [CategoryID] INTEGER PRIMARY KEY AUTOINCREMENT,
        ///       [CategoryName] TEXT,
        ///       [Description] TEXT,
        ///       [Picture] BLOB
        ///);
        ///
        ///INSER [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	CustomerId,
        ///	CompanyName
        ///FROM 
        ///	Customers
        ///WHERE 
        ///	CustomerId = @CustomerId;			.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	CustomerId,
        ///	CompanyName
        ///FROM 
        ///	Customers
        ///WHERE 
        ///	Country = @Country;			.
        /// </summary>
        internal static string CustomersByCountry {
            get {
                return ResourceManager.GetString("CustomersByCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 1 FROM sqlite_master WHERE type=&apos;table&apos; AND name=&apos;Customers&apos;;.
        /// </summary>
        internal static string DatabaseInitializedQuery {
            get {
                return ResourceManager.GetString("DatabaseInitializedQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Customers (CustomerId, CompanyName)
        ///VALUES (@CustomerId, @CompanyName)
        ///
        ///.
        /// </summary>
        internal static string InsertCustomer {
            get {
                return ResourceManager.GetString("InsertCustomer", resourceCulture);
            }
        }
    }
}
